### ISSUE TITLE
Add metric detail page

### ISSUE THREAD

**Issue by heitortsergent** [devbeers/dashboard#7]
Clicking on any metric should take user to a more detailed page of that metric, showing a graph over time, and also metric percentages over past 3, 6, and 12 months.

**Comment by jneto** [comment]
- [x] Add white bordererd box around chart and chart trends (follow metrics style)
- [x] Add color to percentage, indicating negative or positive values
- [x] Make chart component generic
- [x] Use chart component to 'all time signups' and 'all time unique signups'
- [x] Make home page metrics link to detail pages
